### PR TITLE
downgrade grunt from 1.0.1 to 0.4.5 for compatibility for older projects

### PR DESCRIPTION
**Pull request by nirnatan**

### CODE REVIEW

**Comment by paazmaya** [comment]
Probably `peerDependencies` ?

**Comment by paazmaya** [comment]
Older project that cannot upgrade their Grunt, should probably not update anything else...

**Comment by paazmaya** [comment]
Thanks!

**Comment by nirnatan** [comment]
Thanks for the merge 👍 

Can you please publish a new version to npm that includes this change?

**Pull request merged**
