### PR TITLE
Moved to jasmine-npm. Added includeAllSources option.

### PR DESCRIPTION
**Pull request by fiznool**
This is a PR which moves away from the `jasmine-node` library to the official `jasmine` node implementation. There are some breaking changes:

- Removed the myriad of `jasmine-node` options in favour of a single `jasmine` option. This supports the Jasmine node configuration options as [outlined here](http://jasmine.github.io/2.4/node.html#section-Configuration).
- Removed all but a [simple terminal reporter](https://github.com/bcaudan/jasmine-spec-reporter), which is configured via the `jasmine.reporter` option.
- Removed the `coverage.print` option in favour of explicitly listing the types of report needed in the `coverage.report` option.

I've also added support for a couple of new coverage options:

- `includeAllSources`: based on [this PR](https://github.com/jribble/grunt-jasmine-node-coverage/pull/50)
- `watermarks`: for defining the levels at which istanbul will print coverage details in red, yellow and green

In order to get a first working draft, I've had to remove the support for the junit reporter. I think this should be easy enough to add in again if needed.

There are a few breaking changes, so I'd maybe suggest if this is a workable change, the version should be bumped to v1.0.0? Or at least an rc?

If this isn't a direction that you'd prefer to take, I'll be using this code going forward and so I'm happy to start a new npm module with this fork.

Thanks for a great plugin!

### CODE REVIEW

**Comment by paazmaya** [comment]
Awesome!

Pretty big changeset and certainly something that has been waiting for a long time to be done, #35 

Definitely needs a clear entry in the README.md for migrating to `v1.0.0` from the previous, could you add that?

**Comment by fiznool** [comment]
No problem, I'll get that sorted.

**Comment by fiznool** [comment]
Migration guide added. It's been a long time since I used jasmine-node, so I might have gotten some parts of the migration guide wrong. If you could please check it that would be ace :smile: 

Also just to note that this PR should allow most of the currently opened issues to be closed!

**Comment by paazmaya** [comment]
Thank you very much!

**Comment by fiznool** [comment]
Thanks! Looking forward to a new npm release. ☺

**Comment by fiznool** [comment]
Could you create a new npm release please?

**Comment by paazmaya** [comment]
Hups... Will do during this week

**Comment by paazmaya** [comment]
https://github.com/jribble/grunt-jasmine-node-coverage/releases/tag/v1.0.0

That week passed, but here it is. Thank you for the support and possible patience.

**Pull request merged**
